project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: labs.qmd
        text: Labs
      - href: FinalProject.qmd
        text: Final Project
      - href: Resources.qmd
        text: Resources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



